--
-- PostgreSQL database dump
--

\restrict bdA4kWBJzcSOIY7cpVtuY7wk90BUHWGBQWGptncO7xdJ3Cbf6uLzLa1oQWHG7pX

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.1 (Debian 18.1-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Admins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Admins" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "LastLoginAt" timestamp with time zone
);


ALTER TABLE public."Admins" OWNER TO postgres;

--
-- Name: Admins_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Admins" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Admins_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Donations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Donations" (
    "Id" integer NOT NULL,
    "ReceiptId" text NOT NULL,
    "DonationAmount" numeric,
    "Quantity" integer,
    "DonorName" text,
    "DonorEmail" text,
    "SuppliesDescription" text,
    "DonorAccountNumber" text NOT NULL,
    "DonationType" integer NOT NULL,
    "DonationDate" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL
);


ALTER TABLE public."Donations" OWNER TO postgres;

--
-- Name: Donations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Donations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Donations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: HelpRequests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."HelpRequests" (
    "Id" integer NOT NULL,
    "RequestorName" text,
    "RequestorPhoneNumber" text,
    "RequestorEmail" text,
    "RequestType" integer NOT NULL,
    "Status" integer NOT NULL,
    "RequestDescription" text NOT NULL,
    "Longitude" double precision NOT NULL,
    "Latitude" double precision NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public."HelpRequests" OWNER TO postgres;

--
-- Name: HelpRequests_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."HelpRequests" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HelpRequests_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Admins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Admins" ("Id", "Name", "Email", "Username", "PasswordHash", "Role", "IsActive", "CreatedAt", "LastLoginAt") FROM stdin;
2	Admin User	24cs.se.secb@gmail.com	24cs	$2a$11$0JRlK5CkTkXIwqIQBwXAseP9TgWoXVpe6rLjheOIiWNzRLU7BioKK	super_admin	t	2025-12-31 00:58:17.197493+00	\N
\.


--
-- Data for Name: Donations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Donations" ("Id", "ReceiptId", "DonationAmount", "Quantity", "DonorName", "DonorEmail", "SuppliesDescription", "DonorAccountNumber", "DonationType", "DonationDate", "Status") FROM stdin;
\.


--
-- Data for Name: HelpRequests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."HelpRequests" ("Id", "RequestorName", "RequestorPhoneNumber", "RequestorEmail", "RequestType", "Status", "RequestDescription", "Longitude", "Latitude", "CreatedAt", "UpdatedAt") FROM stdin;
2	Farhan Shakeel Shakeel Ahmed	03127474092	farhanshakeel262@gmail.com	2	0	water level rising	74.14774262001453	32.24360220317733	2025-12-31 00:00:23.647923+00	2025-12-31 00:00:23.647924+00
3	Farhan Shakeel Shakeel Ahmed	03127474092	farhanshakeel262@gmail.com	2	0	water	74.14765574085588	32.24354451814033	2025-12-31 00:01:48.330412+00	2025-12-31 00:01:48.330412+00
4	Farhan Shakeel Shakeel Ahmed	03127474092	farhanshakeel262@gmail.com	2	0	qqqqqqq	74.14765574085588	32.24354451814033	2025-12-31 00:03:02.868309+00	2025-12-31 00:03:02.868309+00
5	Farhan Shakeel Shakeel Ahmed	03127474092	farhanshakeel262@gmail.com	2	0	eeeeeee	74.14765574085588	32.24354451814033	2025-12-31 00:03:19.54833+00	2025-12-31 00:03:19.54833+00
6	Farhan Shakeel Shakeel Ahmed	03127474092	farhanshakeel262@gmail.com	2	0	sssssssss	74.2099	32.17	2025-12-31 00:04:09.160512+00	2025-12-31 00:04:09.160512+00
1	Test	03001234567	test@test.com	0	1	Test request	69.3451	30.3753	2025-12-30 23:59:41.994602+00	2025-12-31 01:13:57.972163+00
7	Farhan Shakeel Shakeel Ahmed	03127474092	farhanshakeel262@gmail.com	1	3	eeeeeeeee	74.14770310902617	32.243569133526094	2025-12-31 01:12:17.062641+00	2025-12-31 01:16:13.554038+00
8	Farhan Shakeel Shakeel Ahmed	03127474092	farhanshakeel262@gmail.com	1	0	21de323srcf23	74.14759854037663	32.24351669422279	2026-01-03 05:27:47.201265+00	2026-01-03 05:27:47.201265+00
9	Farhan Shakeel Shakeel Ahmed	03127474092	farhanshakeel262@gmail.com	1	0	i need help	74.1476676597341	32.243530523791094	2026-01-03 05:34:14.277533+00	2026-01-03 05:34:14.277534+00
10	TestUser	03001234567	test@example.com	0	0	Test new request	69.3451	30.3753	2026-01-03 05:37:40.163499+00	2026-01-03 05:37:40.163499+00
11	Adddd	03007474092	\N	1	0	req	74.14764942238433	32.24351578334123	2026-01-03 05:38:24.389892+00	2026-01-03 05:38:24.389892+00
12	list	03007474092	\N	1	0	medical	74.14774262001453	32.24360220317733	2026-01-03 05:39:07.34117+00	2026-01-03 05:39:07.34117+00
13	qwerty	03007474092	\N	1	3	ddddddddd	74.14770098278	32.24356306029593	2026-01-03 05:40:57.15611+00	2026-01-03 05:58:15.898746+00
14	qwerty	03007474092	farhanshakeel123@outlook.com	1	0	sdee\n\nTags: Chronic condition	74.14770098278	32.24356306029593	2026-01-03 07:29:27.917153+00	2026-01-03 07:29:27.917334+00
15	qwerty	03007474092	farhanshakeel123@outlook.com	1	0	efw3w\n\nTags: Chronic condition	74.14768970531765	32.24355423046441	2026-01-03 07:30:03.982762+00	2026-01-03 07:30:03.982762+00
16	qwerty	03007474092	farhanshakeel123@outlook.com	0	1	fever\n\nTags: Illness	74.14768970531765	32.24355423046441	2026-01-03 08:38:01.728558+00	2026-01-03 08:38:35.641835+00
17	qwerty	03007474092	farhanshakeel123@outlook.com	2	1	ssssss\n\nTags: Evacuation needed	74.14766492156993	32.24353756955497	2026-01-03 08:52:45.727204+00	2026-01-03 08:55:28.841854+00
18	qwerty	03007474092	farhanshakeel123@outlook.com	2	3	help\n\nTags: Evacuation needed	74.14768597895947	32.243559083841554	2026-01-03 08:56:03.994947+00	2026-01-03 08:57:16.507025+00
19	qwerty	03007474092	farhanshakeel123@outlook.com	1	2	nail cutter\n\nTags: Hygiene	74.14761914459045	32.243515824830816	2026-01-03 08:57:48.204372+00	2026-01-03 09:01:33.079792+00
20	qwerty	03007474092	farhanshakeel123@outlook.com	1	0	need quickly\n\nTags: Baby supplies, Blankets	74.14773299467713	32.24359164750992	2026-01-04 13:51:49.828762+00	2026-01-04 13:51:49.828895+00
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251228142302_InitialCreate	10.0.0
\.


--
-- Name: Admins_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Admins_Id_seq"', 2, true);


--
-- Name: Donations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Donations_Id_seq"', 1, false);


--
-- Name: HelpRequests_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."HelpRequests_Id_seq"', 20, true);


--
-- Name: Admins PK_Admins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Admins"
    ADD CONSTRAINT "PK_Admins" PRIMARY KEY ("Id");


--
-- Name: Donations PK_Donations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Donations"
    ADD CONSTRAINT "PK_Donations" PRIMARY KEY ("Id");


--
-- Name: HelpRequests PK_HelpRequests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HelpRequests"
    ADD CONSTRAINT "PK_HelpRequests" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Admins_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Admins_Email" ON public."Admins" USING btree ("Email");


--
-- Name: IX_Admins_Username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Admins_Username" ON public."Admins" USING btree ("Username");


--
-- PostgreSQL database dump complete
--

\unrestrict bdA4kWBJzcSOIY7cpVtuY7wk90BUHWGBQWGptncO7xdJ3Cbf6uLzLa1oQWHG7pX

