import { useState } from 'react';
import { loadStripe } from '@stripe/stripe-js';
import Header from './Header';
import Footer from './Footer';
import '../styles/donations.css';

// Initialize Stripe with public key
const stripePromise = loadStripe(import.meta.env.VITE_STRIPE_PUBLIC_KEY);

const Donations = () => {
  // Updated to use "Cash" and "OtherSupplies" as per requirements
  const [donationType, setDonationType] = useState('Cash');
  const [donationData, setDonationData] = useState({
    // Common fields
    donorName: '',
    email: '',
    contact: '',
    
    // Cash donation fields
    amount: '',
    
    // OtherSupplies donation fields
    supplyDetails: '', // Replaces itemName
    quantity: 1,
    description: ''
  });
  
  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitStatus, setSubmitStatus] = useState(null);

  const validateForm = () => {
    const newErrors = {};
    
    // Email validation - required for all donation types
    if (!donationData.email.trim()) {
      newErrors.email = 'Email is required';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(donationData.email)) {
      newErrors.email = 'Please enter a valid email';
    }
    
    // Mobile number validation - required for all donation types
    if (!donationData.contact.trim()) {
      newErrors.contact = 'Mobile number is required';
    } else if (!/^[+]?[0-9\s\-\(\)]{10,}$/.test(donationData.contact)) {
      newErrors.contact = 'Please enter a valid mobile number';
    }
    
    // Cash donation validations
    if (donationType === 'Cash') {
      if (!donationData.amount || donationData.amount <= 0) {
        newErrors.amount = 'Please enter a valid donation amount (must be > 0)';
      }
      // Removed max amount validation as per instruction #4
    }
    
    // OtherSupplies donation validations
    if (donationType === 'OtherSupplies') {
      if (!donationData.supplyDetails.trim()) {
        newErrors.supplyDetails = 'Supply details are required';
      }
      if (!donationData.quantity || donationData.quantity <= 0) {
        newErrors.quantity = 'Please enter valid quantity (must be > 0)';
      }
    }
    
    return newErrors;
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setDonationData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: '' }));
    }
  };

  const handleDonationTypeChange = (type) => {
    setDonationType(type);
    setErrors({});
    // Clear specific fields when switching donation types
    if (type === 'OtherSupplies') {
      setDonationData(prev => ({
        ...prev,
        amount: ''
      }));
    } else if (type === 'Cash') {
      setDonationData(prev => ({
        ...prev,
        supplyDetails: '',
        quantity: 1,
        description: ''
      }));
    }
  };

  const quickAmounts = [500, 1000, 2000, 5000, 10000];

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    const validationErrors = validateForm();
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }
    
    setIsSubmitting(true);
    setSubmitStatus(null);
    
    try {
      const parseJsonSafe = async (response) => {
        const text = await response.text();
        if (!text) return {};
        try { return JSON.parse(text); } catch { return { raw: text }; }
      };
      // Prepare payload according to backend DTO structure (Instruction #3)
      const payload = {
        donationType: donationType === 'Cash' ? 'Cash' : 'OtherSupplies', // Use string values as per enum
        donorName: donationData.donorName || null,
        email: donationData.email,
        contact: donationData.contact,
        
        // Conditional fields based on donation type (Instruction #1)
        ...(donationType === 'Cash' && {
          amount: parseFloat(donationData.amount)
          // Note: AccountNumber is generated by backend, not sent from frontend
          // Note: No more donorAccountNumber field
        }),
        
        ...(donationType === 'OtherSupplies' && {
          quantity: parseInt(donationData.quantity),
          supplyDetails: donationData.supplyDetails,
          description: donationData.description || null
          // Note: No more itemCondition field
        })
      };

      if (donationType === 'Cash') {
        // For Cash donations: call Stripe session creation endpoint (Instruction #4)
        const response = await fetch(`${import.meta.env.VITE_API_BASE}/api/donation/create-session`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(payload)
        });

        const result = await parseJsonSafe(response);

        if (response.ok) {
          if (result.url) {
            // New Stripe.js approach: redirect via URL from backend
            window.location.assign(result.url);
            return;
          }
          if (result.sessionId) {
            // Fallback: no redirectToCheckout in latest Stripe.js; show guidance
            setSubmitStatus({
              success: true,
              message: 'Payment session created. Redirect URL not provided by server. Please contact support.'
            });
          } else {
            throw new Error('No payment URL or session ID received');
          }
        } else {
          setSubmitStatus({
            success: false,
            message: result.message || 'Submission failed. Please try again.'
          });
        }
      } else {
        // For OtherSupplies donations
        const response = await fetch(`${import.meta.env.VITE_API_BASE}/api/donation/create-supplies`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(payload)
        });

        const result = await parseJsonSafe(response);

        if (response.ok) {
          // Show confirmation after successful POST for OtherSupplies (Instruction #5)
          setSubmitStatus({
            success: true,
            message: 'Thank you for your donation! You will receive a confirmation email shortly.',
            receiptId: result.receiptId || result.id
          });
          
          // Reset form
          setDonationData({
            donorName: '',
            email: '',
            contact: '',
            amount: '',
            supplyDetails: '',
            quantity: 1,
            description: ''
          });
        } else {
          setSubmitStatus({
            success: false,
            message: result.message || 'Submission failed. Please try again.'
          });
        }
      }
    } catch (error) {
      setSubmitStatus({
        success: false,
        message: error.message || 'An error occurred. Please try again.'
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="donation-page">
      <Header />
      
      <main className="donation-container">
        <div className="donation-header">
          <h1>Support Flood Relief Efforts</h1>
          <p className="subtitle">Your contribution makes a direct impact on affected communities</p>
          
          <div className="impact-stats">
            <div className="stat-item">
              <span className="stat-number">RS 500</span>
              <span className="stat-label">Feeds a family for 3 days</span>
            </div>
            <div className="stat-item">
              <span className="stat-number">RS 1000</span>
              <span className="stat-label">Provides emergency medical kit</span>
            </div>
            <div className="stat-item">
              <span className="stat-number">RS 5000</span>
              <span className="stat-label">Supports temporary shelter</span>
            </div>
          </div>
        </div>

        <div className="donation-form-wrapper">
          {submitStatus && submitStatus.success && donationType === 'OtherSupplies' && (
            <div className={`status-message ${submitStatus.success ? 'success' : 'error'}`}>
              <div className="confirmation-message">
                <h3>🎉 Thank You for Your Donation!</h3>
                <p>{submitStatus.message}</p>
                {submitStatus.receiptId && (
                  <p className="receipt-id">Receipt ID: <strong>{submitStatus.receiptId}</strong></p>
                )}
                <p>Our team will contact you within 24 hours for collection details.</p>
              </div>
            </div>
          )}

          {submitStatus && !submitStatus.success && (
            <div className="status-message error">
              {submitStatus.message}
            </div>
          )}

          <div className="donation-type-selector">
            <button
              className={`type-btn ${donationType === 'Cash' ? 'active' : ''}`}
              onClick={() => handleDonationTypeChange('Cash')}
              type="button"
            >
              💰 Cash Donation
            </button>
            <button
              className={`type-btn ${donationType === 'OtherSupplies' ? 'active' : ''}`}
              onClick={() => handleDonationTypeChange('OtherSupplies')}
              type="button"
            >
              📦 Other Supplies Donation
            </button>
          </div>

          <form onSubmit={handleSubmit} className="donation-form">
            <div className="form-section">
              <h3>Donation Details</h3>
              
              {/* Show only relevant fields based on donation type (Instruction #1) */}
              {donationType === 'Cash' ? (
                <div className="money-donation">
                  <div className="quick-amounts">
                    {quickAmounts.map(amount => (
                      <button
                        key={amount}
                        type="button"
                        className={`amount-btn ${donationData.amount == amount ? 'selected' : ''}`}
                        onClick={() => setDonationData(prev => ({ ...prev, amount }))}
                      >
                        RS {amount.toLocaleString('en-IN')}
                      </button>
                    ))}
                  </div>
                  
                  <div className="form-group">
                    <label htmlFor="amount">
                      Donation Amount (RS) <span className="required">*</span>
                    </label>
                    <input
                      type="number"
                      id="amount"
                      name="amount"
                      value={donationData.amount}
                      onChange={handleInputChange}
                      placeholder="Enter amount in rupees"
                      min="1"
                      step="0.01"
                      className={errors.amount ? 'error' : ''}
                      disabled={isSubmitting}
                    />
                    {errors.amount && <div className="error-message">{errors.amount}</div>}
                    <p className="field-note">Enter amount greater than 0</p>
                  </div>
                </div>
              ) : (
                <div className="goods-donation">
                  <div className="form-group">
                    <label htmlFor="supplyDetails">
                      Supply Details <span className="required">*</span>
                    </label>
                    <input
                      type="text"
                      id="supplyDetails"
                      name="supplyDetails"
                      value={donationData.supplyDetails}
                      onChange={handleInputChange}
                      placeholder="e.g., Rice, Blankets, Medicines, Water Bottles"
                      className={errors.supplyDetails ? 'error' : ''}
                      disabled={isSubmitting}
                    />
                    {errors.supplyDetails && <div className="error-message">{errors.supplyDetails}</div>}
                  </div>
                  
                  <div className="form-row">
                    <div className="form-group">
                      <label htmlFor="quantity">
                        Quantity <span className="required">*</span>
                      </label>
                      <input
                        type="number"
                        id="quantity"
                        name="quantity"
                        value={donationData.quantity}
                        onChange={handleInputChange}
                        min="1"
                        max="1000"
                        className={errors.quantity ? 'error' : ''}
                        disabled={isSubmitting}
                      />
                      {errors.quantity && <div className="error-message">{errors.quantity}</div>}
                      <p className="field-note">Enter quantity greater than 0</p>
                    </div>
                  </div>
                  
                  <div className="form-group">
                    <label htmlFor="description">Description (Optional)</label>
                    <textarea
                      id="description"
                      name="description"
                      value={donationData.description}
                      onChange={handleInputChange}
                      placeholder="Provide details about the supplies..."
                      rows="3"
                      disabled={isSubmitting}
                    />
                  </div>
                </div>
              )}
            </div>

            <div className="form-section">
              <h3>Your Information</h3>
              
              <div className="form-row">
                <div className="form-group">
                  <label htmlFor="donorName">Full Name (Optional)</label>
                  <input
                    type="text"
                    id="donorName"
                    name="donorName"
                    value={donationData.donorName}
                    onChange={handleInputChange}
                    placeholder="Enter your full name"
                    disabled={isSubmitting}
                  />
                </div>
                
                <div className="form-group">
                  <label htmlFor="email">
                    Email Address <span className="required">*</span>
                  </label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    value={donationData.email}
                    onChange={handleInputChange}
                    placeholder="you@example.com"
                    className={errors.email ? 'error' : ''}
                    disabled={isSubmitting}
                  />
                  {errors.email && <div className="error-message">{errors.email}</div>}
                </div>
              </div>
              
              <div className="form-row">
                <div className="form-group">
                  <label htmlFor="contact">
                    Mobile Number <span className="required">*</span>
                  </label>
                  <input
                    type="tel"
                    id="contact"
                    name="contact"
                    value={donationData.contact}
                    onChange={handleInputChange}
                    placeholder="+91 98765 43210"
                    className={errors.contact ? 'error' : ''}
                    disabled={isSubmitting}
                  />
                  {errors.contact && <div className="error-message">{errors.contact}</div>}
                </div>
                
                {/* Removed donorAccountNumber field as AccountNumber is generated by backend */}
              </div>
            </div>

            <div className="form-footer">
              <p className="disclaimer">
                By submitting this form, you agree that your donation will be used for flood relief efforts.
                {donationType === 'Cash' && ' All transactions are secure and processed through Stripe.'}
                {donationType === 'OtherSupplies' && ' Our team will contact you within 24 hours for collection details.'}
              </p>
              
              <button
                type="submit"
                className="submit-btn"
                disabled={isSubmitting}
              >
                {isSubmitting ? (
                  <>
                    <span className="spinner"></span>
                    Processing...
                  </>
                ) : donationType === 'Cash' ? (
                  'Proceed to Payment'
                ) : (
                  'Submit Donation'
                )}
              </button>
            </div>
          </form>
          
          <div className="security-info">
            {donationType === 'Cash' ? (
              <>
                <h4>💳 Secure Payment</h4>
                <p>All cash donations are processed securely through Stripe</p>
                
                <h4>📄 Tax Benefits</h4>
                <p>All donations are eligible for tax deductions under Section 80G</p>
                
                <h4>🔒 Data Protection</h4>
                <p>Your payment information is encrypted and secure</p>
              </>
            ) : (
              <>
                <h4>📦 Supplies Collection</h4>
                <p>Our team will contact you within 24 hours for pickup details</p>
                
                <h4>✅ Accepted Supplies</h4>
                <p>Food, clothing, medicines, blankets, water, and other essentials</p>
                
                <h4>📍 Drop-off Points</h4>
                <p>Multiple collection centers available across the city</p>
              </>
            )}
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default Donations;